Repository eastsage/the-dapda, pull requests merged in 2024-09, with the labels that each got.

#4 :sparkles: Feat: open-ai api 테스트, PR 템플릭 적용, 패키지 구조 예시 코드 반영
  src/main/java/com/the_dapda/domain/ai/controller/.gitkeep
  src/main/java/com/the_dapda/domain/ai/controller/ChatController.java
  src/test/java/com/the_dapda/TheDapdaApplicationTests.java
Labels: 😒chore, 💥feature

#10 Feat - AI 일기 답변 기능, AI 질문 생성 기능, 카테고리 별 프롬프트 저장 기능 구현
  src/main/java/com/the_dapda/domain/ai/controller/ChatController.java
  src/main/java/com/the_dapda/domain/ai/dto/.gitkeep
  src/main/java/com/the_dapda/domain/ai/dto/request/ChatRequestDto.java
  src/main/java/com/the_dapda/domain/ai/dto/response/ChatResponseDto.java
  src/main/java/com/the_dapda/domain/ai/service/.gitkeep
  src/main/java/com/the_dapda/domain/ai/service/ChatService.java
  src/main/java/com/the_dapda/domain/category/controller/CategoryQueryController.java
  src/main/java/com/the_dapda/domain/category/dto/request/SavePromptRequestDto.java
  src/main/java/com/the_dapda/domain/category/entity/Category.java
  src/main/java/com/the_dapda/domain/category/repository/CategoryRepository.java
  src/main/java/com/the_dapda/domain/category/service/CategoryQueryService.java
  src/main/java/com/the_dapda/domain/category/service/impl/CategoryQueryServiceImpl.java
  src/main/java/com/the_dapda/domain/diary/controller/.gitkeep
  src/main/java/com/the_dapda/domain/diary/controller/DiaryCommandController.java
  src/main/java/com/the_dapda/domain/diary/dto/.gitkeep
  src/main/java/com/the_dapda/domain/diary/dto/request/DiarySaveRequest.java
  src/main/java/com/the_dapda/domain/diary/entity/.gitkeep
  src/main/java/com/the_dapda/domain/diary/entity/Diary.java
  src/main/java/com/the_dapda/domain/diary/repository/.gitkeep
  src/main/java/com/the_dapda/domain/diary/service/.gitkeep
  src/main/java/com/the_dapda/domain/diary/service/command/impl/DiaryCommandServiceImpl.java
  src/main/java/com/the_dapda/domain/diary/service/query/impl/DiaryQueryServiceImpl.java
  src/main/java/com/the_dapda/domain/example/controller/MatchingController.java
  src/main/java/com/the_dapda/domain/example/converter/MatchingListToDto.java
  src/main/java/com/the_dapda/domain/example/dto/BannerListResponse.java
  src/main/java/com/the_dapda/domain/example/entity/Matching.java
  src/main/java/com/the_dapda/domain/example/entity/Status.java
  src/main/java/com/the_dapda/domain/example/repository/MatchingRepository.java
  src/main/java/com/the_dapda/domain/example/repository/MatchingRepositoryImpl.java
  src/main/java/com/the_dapda/domain/example/service/MatchingService.java
  src/main/java/com/the_dapda/domain/example/service/MatchingServiceImpl.java
  src/main/java/com/the_dapda/global/security/config/SecurityConfiguration.java
Labels: 😒chore, 😉enhancement, 💥feature, 😎refactor

#12 Feat: 메인, 질문 카테고리 선택 페이지 추가
  src/main/resources/static/css/mobile-frame.css
  src/main/resources/templates/login.html
  src/main/resources/templates/main.html
  src/main/resources/templates/select-question.html
  src/main/resources/templates/signup.html
Labels: 💥feature

#13 Feat/ai
  src/main/java/com/the_dapda/domain/ai/dto/request/ChatRequestDto.java
  src/main/java/com/the_dapda/domain/ai/service/ChatService.java
  src/main/java/com/the_dapda/domain/ai/service/impl/ChatServiceImpl.java
  src/main/java/com/the_dapda/domain/diary/service/command/impl/DiaryCommandServiceImpl.java
  src/main/java/com/the_dapda/global/security/config/SecurityConfiguration.java
Labels: 😒chore, 😉enhancement, 😎refactor

#21 Refactor: select-question에서 Category를 서버에서 받아서 출력하도록 수정
  src/main/resources/templates/main.html
  src/main/resources/templates/select-question.html
Labels: 😎refactor

#22 Fix: 로그인 이후 security session의 유저 정보를 이용하도록 수정
  src/main/java/com/the_dapda/domain/diary/controller/DiaryQueryController.java
Labels: 😎refactor

#27 Feat: main & view-diary 연결 및 삭제 기능 구현
  src/main/java/com/the_dapda/domain/diary/controller/DiaryCommandController.java
  src/main/java/com/the_dapda/domain/diary/controller/DiaryQueryController.java
  src/main/java/com/the_dapda/domain/diary/dto/response/DiaryResponse.java
  src/main/java/com/the_dapda/domain/diary/repository/DiaryRepository.java
  src/main/java/com/the_dapda/domain/diary/service/query/DiaryQueryService.java
  src/main/java/com/the_dapda/domain/diary/service/query/impl/DiaryQueryServiceImpl.java
  src/main/resources/templates/main.html
  src/main/resources/templates/view-diary.html
Labels: 💥feature

#28 Feat: AI 응답을 기다리는 UI 추가 및 오늘 일기가 안보이는 오류 수정
  src/main/resources/templates/main.html
  src/main/resources/templates/select-question.html
  src/main/resources/templates/view-diary.html
  src/main/resources/templates/view-question.html
Labels: 😶‍🌫️bug, 💥feature
